#!/usr/bin/env bash

# usage info
usage() {
  cat <<EOF
  Usage: git docker-bash [options]
  Options:
    id                      Container-Id to start bash in.
    -n, --name              Use name of container to stat bash.
    -h, --help              This message.
    --                      End of options.
EOF
}

VERSION=0.1
name=0

# Parse options
while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
  case $1 in
    -v | --version )
      echo $version
      exit
      ;;
    -h | --help )
      usage
      exit
      ;;
    -n | --name )
      name=1
      ;;
    * )
      echo "abort: unknown argument" 1>&2
      exit 1
  esac
  shift
done

if [[ "$1" == "--" ]]; then shift; fi

function start_bash() {
  echo -e "Starting bash in docker container ${1}\n"
  docker exec -it ${1} /bin/bash
}

function choose_from_list() {
  index=-1
  IFS=$'\r\n' read -r -d '' -a container_ids <<< "$(docker ps -q ${1})"

  docker ps ${1} |  while IFS= read -r line
    do
      if [ "$index" -eq -1 ]; then
        echo "    $line"
      else
        echo "[$index] $line"
      fi;
      ((index++))
  done

  read -p "Enter container index: " container_index

  if [[ ! -z ${container_ids[$container_index]} ]]; then
    start_bash ${container_ids[$container_index]}
  else
    echo -e "Invalid index. \nChoose from the list: "

    choose_from_list ''
  fi
}

if [[ -n $1 && ${name} == "0" ]];  then

  found_container="$(docker ps -q -f id=$1)"
  if [ "$found_container" ]; then
    start_bash $found_container
  else
    echo -e "No container found with id '$1'.\n\nGo ahead and choose from the list:"
    choose_from_list ''
  fi

elif [ ${name} == "1" ]; then

  IFS=$'\r\n' read -r -d '' -a container_ids <<< "$(docker ps -q -f name=${1})"
  
  if [[ "${#container_ids[@]}" == 1 ]]; then
    start_bash ${container_ids[0]}
  elif [[ "${#container_ids[@]}" == 0 ]]; then
    echo -e "Did find any matches for '${1}', here are all running containers:\n"
    choose_from_list ''
  else
    echo -e "Found more than one match:\n"
    choose_from_list "-f name=${1}"
  fi

else

  choose_from_list ''

fi
